### PR TITLE
#2 Text data check, cleaning, and preprocessing; 1) Remove punctuations & stop words, 2) Tokenization 3) Stemming (Irene)

### PR DESCRIPTION
**Pull request by irodriguezclaveria**
Task related:
 https://github.com/SDG-AI-Lab/Team-5-Crisis-Informatics/issues/12

To check install libraries:

NLTK
Panda
sklearn

Considerations:

- **That just is a piece of prototype code  that works with words tokenizer**(remove punctuations, stop words, stemming)
- The data is showed in a data frame, but this can be changed in another format as CSV, just is a prototype to show the data.
- I'm using the dataset attached in the folder with the same name, for this prototype just I'm using the twitter column.
- I'm using CountVectorizer, this tool by default put the works in lower case and ignore the punctuations.
- The CountVectorize, tokenize the text and vectorize the words, this way you can obtain different data as the frequency of words.
-  This code just works for use with words, **this piece of code is not valid to clean data in the pull request of labelled sentiments and geocode, because to clean this data I have to work over the complete tweet not the word,** I will create another pull request for this propose.

### CODE REVIEW

**Comment by ulie50** [comment]
Hi Irene, I was running your modules on my PC and have a little suggestion: what if to add a requirements.txt with all the dependencies for your code so that virtual environment can be deployed out of it and then there will be no need to isntall missing libraries one by one and also it will be easier to implement it as part of API. 
In my case nltk was missing but after installation I anyway had to add a couple of lines to your code in the beginning to make it work on my PC ( import nltk; nltk.download('stopwords')). What do you think?

**Comment by ulie50** [comment]
By first run it somehow did not recognize "from nltk.corpus import stopwords" but now it does after i ran it with those two lines and removed. Probably I had to download stopwords along with library

**Comment by shivangisareen** [comment]
Adding my comment to the PR conversation - 

Hi @irodriguezclaveria, this looks great!
I have a couple of changes in mind -
• Add a doc-string for each function to talk about what the function does
• Change the main.py file to show the flow of functions instead of doing it in the preprocessing_data.py file. This will also help when we have to create a data pipeline
• Creating an output file for the tokenised and cleaned tweets instead of printing it out

I am working on these changes and will push them by EOD today. Let me know what you all think!

**Comment by shivangisareen** [comment]
Pushed code for #1 and #2 points. I haven't yet pushed the code for creating an output file of tokenised and clean tweets.

**Pull request merged**
